package ar.unrn.tp.modelo;
//Agregar categorías dinámicas
public enum Categoria {
    CALZADO, ROPA_DEPORTIVA, ACCESORIOS, ELECTRONICA, HOGAR, MUEBLES, JUGUETES, LIBROS, MUSICA, PELICULAS, COMESTIBLES, BEBIDAS, LIMPIEZA, MASCOTAS, AUTOMOTOR, OTROS
}
